# application: data-entry-demo
# version: master
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html
  secure: always

- url: /(.+)
  static_files: \1/index.html
  upload: (.+)/index.html
  secure: always

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)
  secure: always

- url: /(.*\.js)
  mime_type: text/js
  static_files: \1
  upload: (.*\.js)
  secure: always
